<div class="iconNav" id="iconNav">
  <div class="icon_menu">
    <div class="icon_inner"></div>
  </div>
</div>
<div class="bHeader">
  <h1 class="logo">
    <a href="/"><img src="/common/images/logo.png" alt="PEARLY GATES"></a>
  </h1>
  <!--/.logo-->
  <nav class="nav" id="nav">
    <dl class="nav_menu">
      <dt class="nav_ttl"><i class="icon01"><img src="/common/images/icon_nav_01.png" alt=""></i>売上情報</dt>
      <dd>
        <ul class="nav_list">
          <li><a href="/sales/schedule.html">入力</a></li>
          <li><a href="/sales/">照会</a></li>
        </ul>
      </dd>
    </dl>
    <dl class="nav_menu">
      <dt class="nav_ttl"><i class="icon02"><img src="/common/images/icon_nav_02.png" alt=""></i>お客様情報</dt>
      <dd>
        <ul class="nav_list">
          <li><a href="/customers/edit.html">入力</a></li>
          <li><a href="/customers/">照会</a></li>
          <li><a href="/customers/log.html">閲覧ログ</a></li>
        </ul>
      </dd>
    </dl>
    <dl class="nav_menu">
      <dt class="nav_ttl"><i class="icon03"><img src="/common/images/icon_nav_03.png" alt=""></i>マーケティング</dt>
      <dd>
        <ul class="nav_list">
          <li><a href="/marketing/ranking-products.html">売上高順位</a></li>
          <li><a href="/marketing/csv-download-period.html">抽出</a></li>
          <li><a href="/marketing/history.html">利用履歴</a></li>
          <li><a href="/marketing/staff.html">スタッフ管理</a></li>
        </ul>
      </dd>
    </dl>
  </nav>
  <!--/.nav-->
</div>
<!--/.bHeader-->